import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Sidebar from "./sidebar"; // Import the Sidebar
import { ConvexClientProvider } from "./components/ConvexClientProvider";
import { StateProvider } from "./components/StateContext";




export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (

    <html lang="en" className="h-full">
      <body>
        <ConvexClientProvider>
          <StateProvider>
            <div className="flex h-full fixed main">
              <div className="mainDiv">
                {/* Sticky Sidebar */}
                <div className="hidden sm:block sticky h-screen z-20">
                  <Sidebar />
                </div>
                {/* Scrollable Main Content Area */}
                <div className="flex-1 overflow-y-auto h-screen z-10">
                  {children}
                </div>
              </div>
            </div>
          </StateProvider>
        </ConvexClientProvider>
      </body>
    </html>
  );
}
